Repository nicolasfara/ecscala, pull requests merged in 2021-10, with the labels that each got.

#134 Retrospective Sprint 8
  doc/1-development-process.tex
  doc/6-retrospective.tex
  process/product-backlog.csv
Labels: report

#136 Fix bug with components update
  core/src/main/scala/dev/atedeg/ecscala/Entity.scala
  core/src/main/scala/dev/atedeg/ecscala/util/mutable/ComponentsContainer.scala
  core/src/test/scala/dev/atedeg/ecscala/WorldTest.scala
  demo/src/main/scala/dev/atedeg/ecscalademo/controller/MainViewController.scala
Labels: bug

#144 Add demo skeleton
  doc/6-demo.tex
  doc/7-retrospective.tex
  doc/ecscala-report.tex
Labels: report

#143 Development Process
  doc/1-development-process.tex
  doc/5-implementation.tex
  doc/7-retrospective.tex
  process/organizational-sprint.md
Labels: report

#150 Add AutoPauseSystem
  demo/src/main/scala/dev/atedeg/ecscalademo/controller/MainViewController.scala
  demo/src/main/scala/dev/atedeg/ecscalademo/systems/AutoPauseSystem.scala
  demo/src/test/scala/dev/atedeg/ecscalademo/fixtures/AutoPauseSystemFixture.scala
  demo/src/test/scala/dev/atedeg/ecscalademo/systems/AutoPauseSystemTest.scala
Labels: feature

#149 Demo detailed design
  doc/6-demo.tex
  doc/img/fsm-demo.eps
Labels: report
